config/routes.rb
Warstler::Application.routes.draw do

  resources :pages

  root to: 'pages#index'

  get 'reception' => 'pages#reception', :as => :reception
  get 'ourstory' => 'pages#ourstory', :as => :ourstory
  get 'registry' => 'pages#registry', :as => :registry
  
end

app/models/page.rb
class Page < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :authenticate

  def authenticate
    if Rails.env.staging?
      authenticate_or_request_with_http_basic do |username, password|
        username == ENV["HTTP_USERNAME"] && password == ENV["HTTP_PASSWORD"]
      end
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
    @pages = Page.all
    @page_name = 'home'
    @page_image = 'sharon-todd-sunset-logo.jpg'
    @title = 'Sharon & Todd'

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pages }
    end
  end

  def show
    @page = Page.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @page }
    end
  end

  def new
    @page = Page.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @page }
    end
  end

  def edit
    @page = Page.find(params[:id])
  end

  def create
    @page = Page.new(params[:page])

    respond_to do |format|
      if @page.save
        format.html { redirect_to @page, notice: 'Page was successfully created.' }
        format.json { render json: @page, status: :created, location: @page }
      else
        format.html { render action: "new" }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @page = Page.find(params[:id])

    respond_to do |format|
      if @page.update_attributes(params[:page])
        format.html { redirect_to @page, notice: 'Page was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @page = Page.find(params[:id])
    @page.destroy

    respond_to do |format|
      format.html { redirect_to pages_url }
      format.json { head :no_content }
    end
  end

  def reception
    @page_name = 'reception'
    @page_image = 'sharon-todd-cheeky.jpg'
    @title = "Sharon & Todd's Reception"
  end

  def ourstory 
    @page_name = 'ourstory'
    @page_image = 'sharon-todd-beach.jpg'
    @title = "Sharon & Todd's Story"
  end

  def registry
    @page_name = 'registry'
    @page_image = 'sharon-todd-umbrella.jpg'
    @title = "Sharon & Todd's Registry"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title><%= @title %></title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= stylesheet_link_tag    "http://fonts.googleapis.com/css?family=Crete+Round" %>
    <%= stylesheet_link_tag    "http://fonts.googleapis.com/css?family=Francois+One" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>

    <% unless Rails.env.development? %>
      <script type="text/javascript">

        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-38686877-1']);
        _gaq.push(['_trackPageview']);

        (function() {
         var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
         ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
         var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
         })();
       </script>
    <% end %> 

  </head>

  <body id="<%= @page_name %>">
    <div class='top'>
      <%= image_tag @page_image %>
    </div>

    <div class='bump'></div>
    <div style="clear:both;">&nbsp;</div>
    <div class='zag'></div>
    <div id='menu'>
      <li id='menunav'><%= link_to 'Sharon & Todd', '/', id:'homenav' %></li>
      <li id='menunav'><%= link_to 'Our Story', 'ourstory', id:'ourstorynav' %></li>
      <li id='menunav'><%= link_to 'Reception', 'reception', id:'receptionnav' %></li>
      <li id='menunav'><%= link_to 'Registry', 'registry', id:'registrynav' %></li>
    </div>

    <div class='bump'></div>
    <%= yield %>

  </body>

  <div class="bump"></div>
  <div class="bump"></div>
  <div class="bump"></div>

  <div class='footer'>
    <%= image_tag '/assets/bring-your-dancing-shoes.png' %>
  </div>
  <div style="clear:both;">&nbsp;</div>
  <div class="bump"></div>
  <p style="text-align:center;font-size:11px;"><strong><em><a href="http://twitter.com/vcabansag">Site built by the brother of the bride</a></em></strong></p>

</html>

app/views/pages/_form.html.erb
<%= form_for(@page) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Editing page</h1>

<%= render 'form' %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<div class='container'>
  <div class='bump'></div>
  <div class="fourcol_3">
    <blockquote>We got married and now it's time to celebrate! We can't ask for anything more than to have our family and friends together in one place.  Hope you can make it!</blockquote>
  </div>
  <div class="fourcol">
    <div class="count">
      <p>Celebrating for:</p>
      <h1><%= (Date.new(2013, 4, 13) - Date.today).to_i.abs %> days</h1>
    </div>
  </div>
  <div class='bump'></div>
  <div style="clear:both;">&nbsp;</div>

  <div class="twocol sharon">
    <img src="assets/sharon.jpg" alt="Sharon">
    <h1 class="profile">Mrs</h1>
    <p>Hey it's Sharon! I'm totally in love and I can't wait to spend the rest of my days with Mr. Warstler.</p> 
    <p style="font-style:italic;color:#aaa;">I kind of have a thing for Him →</p>
  </div>

  <div class="twocol todd">
    <img src="assets/todd.jpg" alt="Todd">
    <h1 class="profile">Mr</h1>
    <p>Hey it's Todd! Sharon is one of a kind and I can't wait to celebrate our marriage with all of you!</p> 
    <p style="font-style:italic;color:#aaa;">← I kind of have a thing for Her</p>
  </div>
  <div style="clear:both;">&nbsp;</div>
</div>

app/views/pages/new.html.erb
<h1>New page</h1>

<%= render 'form' %>

<%= link_to 'Back', pages_path %>

app/views/pages/ourstory.html.erb
<div class='container'>

  <div class="onecol">
    <!-- <<a href="" class="fade"> </a> -->
    <!-- <p style="width:375px;font-size:14px;"><em></em></p> -->
    <div class='ourstory'>
      <p>
      Sharon and Todd first met during middle school.  Sharon had a crush on Todd so she invited him to go downhill skiing and he joyfully accepted.  During high school Sharon and Todd were both interested in dating but Todd was too late as Sharon started dating someone else.  However, Sharon and Todd would reconnect via email every few years as their lives took them in different directions.  Sharon would send Todd emails about cheesy pickup lines and so on.</p>

      <p>In 2009, Todd was living in Maine and Sharon was back in Sturgis.  They reconnected through Facebook and Todd immediately knew that he had to invite Sharon to Sugarloaf, his favorite ski destination.  She hesitated since she hadn't skied in 20 years but Todd promised he wouldn't let her break any bones.  Sharon was so happy that she made the trip out to Maine because she had a blast skiing, eating lobster and playing with Todd's dog Toby.  This rekindled their feelings and they committed to see one another at least once a month thereafter.</p>

      <p>Despite Todd's repeated attempts to get Sharon to move closer to Maine and him, Sharon kept working in Michigan. After marrying off both her siblings, Sharon and Todd finally decided it was time to tie the knot too.  Having a passion for beaches and traveling, they secretly ran away to a beach in November and got married.  They chose St. John, U.S. Virgin Islands as neither had been there before and it boasted some of the worlds most beautiful beaches. They rented a waterfront villa and had an intimate wedding on the beach in between the raindrops. They say rain on your wedding day is good luck, so please come with your best wishes for Sharon and Todd as they celebrate their new life together!</p>
    </div>
  </div>

</div>

app/views/pages/reception.html.erb
<div class='container'>

  <div class="bump"></div>

  <div class="sixcol">
    <h3 class="nomar">Reception</h3>
  </div>

  <div class="directions">
    <p style="color:#000; font-size:20px; margin-top:3px;">
      <%= link_to 'Cityscape Events', 'http://www.millenniumrestaurants.com/cityscape-events/' %>
    </p>
    <p style="line-height:1.8em;">
    125 South Kalamazoo Mall<br />
    Kalamazoo, Michigan
    </p>
    <!-- <p style="color:#68bca5;">See map to the right. →</p> -->
    <p><span style="color:#000; font-size:16px;">April 13, 2013 at 5:00pm</span><br></p>

    <!--
    From the South To CITYSCAPE EVENTS from US-131 
    Exit US-131 at EXIT 36 A … He ad EAST on STADIUM DRIVE … continue onto WEST MICHIGAN AVENUE … SLIGHT RIGHT to stay on West Michigan Avenue… Proceed in right lane and go one block past RADISSON PLAZA HOTEL to intersection at PORTAGE RD… Turn RIGHT (SOUTH) onto PORTAGE RD… Parking ramp entrance is 100 feet ahead on RIGHT. The skywalk to CITYSCAPE EVENTS is on the THIRD LEVEL of the parking structure. 
    To CITYSCAPE EVENTS from I-94 
    Take the KILGORE / PORTAGE RD exit, EXIT #78 … Head WEST on East KILGORE RD toward PORTAGE RD … turn RIGHT at PORTAGE ST … keep LEFT to stay on Portage St … Parking ramp entrance will be on LEFT. The skywalk to CITYSCAPE EVENTS is on the THIRD LEVEL of the parking structure. 
    -->

  </div>

  <div class="directions">
    <div style="border:5px solid #cbd500;">
      <iframe width="370" height="370" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.com/maps?hl=en&amp;q=125+South+Kalamazoo+Mall,+Kalamazoo,+MI&amp;ie=UTF8&amp;hq=&amp;hnear=125+South+Kalamazoo+Mall,+Kalamazoo,+MI&amp;gl=us&amp;t=m&amp;iwloc=A&amp;output=embed"></iframe>
    </div>
    <p><%= link_to "View the larger map", "https://maps.google.com/maps?hl=en&q=125+South+Kalamazoo+Mall,+Kalamazoo,+MI&ie=UTF8&hq=&hnear=125+South+Kalamazoo+Mall,+Kalamazoo,+MI&gl=us&t=m&view=map" %></p>
  </div>

  <div style="clear:both;">&nbsp;</div>
  
  <div class="bump">&nbsp;</div>
  <div style="width:780px;margin-left:170px;margin-bottom:30px;">
    <div class="rule">&nbsp;</div>
  </div>
  <div class="bump">&nbsp;</div>

  <div class="sixcol">
    <h3 class="nomar">Hotels</h3>
  </div>

  <div class="directions">
    <p style="color:#000; font-size:20px; margin-top:3px;">
      <%= link_to 'Radisson Plaza Hotel', 'http://www.radissonkzoo.com' %>
    </p>
    <p style="line-height:1.8em;}">
      100 West Michigan Ave <br />
      Kalamazoo, Michigan<br />
      269.343.3333<br />
    </p>
    <!-- 
    <p>
      The Radisson is walking distance to the reception. They have a pool, fitness center, hot tub, free internet access in the business center, and free airport shuttle. Parking costs $20/day for valet and $15/day for ramp parking. Self parking in the hotel's attached ramp cost $2/hour with a $20/day max.
    </p>
    <p>
      Mention the Cabansag-Warstler wedding for a discounted room rate of $159/night (tax not included). Make sure to book before March 22, 2013 as this hotel often sells out.
    </p>
    -->
  </div>

  <div class="directions">
    <p style="color:#000; font-size:20px; mrgin-top:3px;">
      <%= link_to 'Four Points by Sheraton', 'http://www.fourpointskalamazoo.com' %>
    </p>
    <p style="line-height:1.8em;">
      3600 East Cork Street<br />
      Kalamazoo, Michigan<br />
      269.385.3922<br />
    </p>
    <!-- 
    <p>
      Located about 4 miles or 10 minutes from the reception. The Four Points' rooms includes free wireless internet and the hotel has a pool, fitness center, and free airport shuttle. Parking is free!
    </p>
    <p>
      Mention the Cabansag-Warstler wedding for a discounted room rate $89/night (tax not included). Rooms must be booked by March 15, 2013. 
    </p>
    -->
  </div>


  <div style="clear:both;">&nbsp;</div>

  <div class="bump">&nbsp;</div>
  <div style="width:780px;margin-left:170px;margin-bottom:30px;">
    <div class="rule">&nbsp;</div>
  </div>
  <div class="bump">&nbsp;</div>

  <div class="sixcol">
    <h3 class="nomar">Vendors</h3>
  </div>

  <div class="directions">
    <ul class="details" >
      <li class="vendor"><%= link_to "Dorothy's Floral Studio", 'http://www.dorothysfloralstudio.com/', html_options = { title: "Dorothy's Floral Studio", target: 'blank' } %></li>
      <li class="vendor"><%= link_to 'Kzoom Wedding Videography', 'http://www.kzoomweddings.com/', html_options = { title: "Kzoom Wedding Videography", target: 'blank' } %></li>
      <li class="vendor"><%= link_to 'Loon Lake Photography', 'http://www.loonlakephotography.com/', html_options = { title: "Loon Lake Photography", target: 'blank' } %></li>
    </ul>
  </div>

  <div class="directions">
    <ul class="details" >
      <li class="vendor"><%= link_to 'Boonzaaijer Bakery', 'http://boonzaaijerbakery.com/', html_options = { title: "Boonzaaijer Bakery", target: 'blank' } %></li>
      <li class="vendor"><%= link_to 'Mobile Music DJ', 'http://www.mobilemusicdj.com/', html_options = { title: "Mobile Music DJ", target: 'blank' } %></li>
      <li class="vendor"><%= link_to "David's Bridal", 'http://www.davidsbridal.com/', html_options = { title: "David's Bridal", target: 'blank' } %></li>
    </ul>
  </div>

</div>

app/views/pages/registry.html.erb
<div class='container'>

  <div class="twocol">
    <!-- <p>Click the logos below to view our registry.</p> -->
  </div>

  <div style="clear:both;">&nbsp;</div> 

  <div class="onecol">
    <a href="" class="fade">
      <div class='registry'><%= link_to "Bed Bath and Beyond", 'http://www.bedbathandbeyond.com/regGiftRegistry.asp?wrn=-1152966817&', :class => 'registry-link' %></div>
    </a>
    <p style="width:375px;font-size:14px;"><em></em></p>
  </div>

  <div class="onecol">
    <a href="" class="fade">
      <div class='registry'><%= link_to "Macy's", 'http://www1.macys.com/registry/wedding/guest/?registryId=270169', :class => 'registry-link' %></div>
    </a>
    <p style="width:375px;font-size:14px;"><em></em></p>
  </div>

  <div style="clear:both;">&nbsp;</div> 

</div>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>

app/views/pages/weddingdetails.html.erb
<div class='container'>

  <div class="bump"></div>

  <div class="sixcol">
    <h3 class="nomar">Where/When</h3>
  </div>

  <div class="directions">
    <p style="color:#000; font-size:20px; margin-top:3px;">Celebration</p>
    <p>the celebration will begin at 5:00pm at cityscape events. the address is <strong>125 south kalamazoo mall,kalamazoo, michigan</strong>.</p>
    <p style="color:#68bca5;">see map to the right. →</p>
    <p><span style="color:#000; font-size:16px">Directions:</span><br></p>
Four Points by Sheraton
3600 East Cork Street
Kalamazoo, Michigan, 49001 
(269) 385-3922
Located about 4 miles or 10 minutes from the reception. This room includes free wireless internet.  Hotel has a pool, fitness center, and free airport shuttle. 

Parking: Free
Room rate $89/night. Tax not included.
A block of rooms have been reserved under Cabansag/Warstler wedding. Rooms must be book by March 15, 2013.

http://www.fourpointskalamazoo.com/
  </div>

  <div class="directions">
    <div style="border:5px solid #cbd500; margin-top:45px;">
      <iframe width="370" height="370" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.com/maps?hl=en&amp;q=125+South+Kalamazoo+Mall,+Kalamazoo,+MI&amp;ie=UTF8&amp;hq=&amp;hnear=125+South+Kalamazoo+Mall,+Kalamazoo,+MI&amp;gl=us&amp;t=m&amp;iwloc=A&amp;output=embed"></iframe>
    </div>
    <p><%= link_to "View the larger map", "https://maps.google.com/maps?hl=en&q=125+South+Kalamazoo+Mall,+Kalamazoo,+MI&ie=UTF8&hq=&hnear=125+South+Kalamazoo+Mall,+Kalamazoo,+MI&gl=us&t=m&view=map" %></p>
  </div>

  <div class="directions">
    <p style="color:#000; font-size:20px; margin-top:3px;">Accomodations</p>
    <p>the celebration will begin at 5:00pm at cityscape events. the address is <strong>125 south kalamazoo mall,kalamazoo, michigan</strong>.</p>
    <p style="color:#68bca5;">see map to the right. →</p>
    <p><span style="color:#000; font-size:16px">Radisson Plaza Hotel:</span><br></p>
    <p>
    Radisson Plaza Hotel<br/>
    100 West Michigan Ave<br/>
    Kalamazoo, Michigan, 49007 <br/>
    (269) 343-3333<br/>
    </p>
    <p>
    Within walking distance to the reception. Hotel has a free internet access in business center, pool, hot tub, fitness center, and free airport shuttle. 

    Parking:
    Valet $20/day
    Ramp parking $15/night
    Self parking in hotel's attached ramp is also available at an hourly rate of $2.00 with a $20.00 per day max.
    Room rate: $159/night. Tax not included.
    Rooms must be booked before March 22, 2013. Book early as this hotel often sells out.

    http://www.radissonkzoo.com/
    </p>



  <div style="clear:both;">&nbsp;</div>

  <div style="width:780px;margin-left:170px;margin-bottom:30px;">
    <div class="rule">&nbsp;</div>
  </div>

  <div class="bump">&nbsp;</div>

  <div class="sixcol">
    <h3 class="nomar">Vendors</h3>
  </div>

  <div class="directions">
    <p style="color:#000; font-size:20px;marginheightgin-top:3px;">Vendors:</p>
    <ul class="details">
      <li><%= link_to "Dorothy's Floral Studio", 'http://www.dorothysfloralstudio.com/', html_options = { title: "Dorothy's Floral Studio", target: 'blank' } %></li>
      <li><%= link_to 'Kzoom Wedding Videography', 'http://www.kzoomweddings.com/', html_options = { title: "Kzoom Wedding Videography", target: 'blank' } %></li>
      <li><%= link_to 'Loon Lake Photography', 'http://www.loonlakephotography.com/', html_options = { title: "Loon Lake Photography", target: 'blank' } %></li>
      <li><%= link_to 'Boonzaaijer Bakery', 'http://boonzaaijerbakery.com/', html_options = { title: "Boonzaaijer Bakery", target: 'blank' } %></li>
      <li><%= link_to 'Mobile Music DJ', 'http://www.mobilemusicdj.com/', html_options = { title: "Mobile Music DJ", target: 'blank' } %></li>
      <li><%= link_to "David's Bridal", 'http://www.davidsbridal.com/', html_options = { title: "David's Bridal", target: 'blank' } %></li>
    </ul>
  </div>

</div>
</div>
<div style="clear:both;">&nbsp;</div>

Here is a collection of information links we thought may be helpful regarding hotels, restaurants and things to do and see while visiting Kalamazoo.  If you are looking for something specific, please let us know! For all hotels listed, we have reserved a block of rooms at a discounted rate.  Please be sure to mention you are with the Cabansag/Warstler wedding in order to enjoy the discount. 